<a href="https://colab.research.google.com/github/m0l0t0v-eng/Calculadora/blob/Mejoras-de-c%C3%B3digos/t4_mat2121_fa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Análisis de Datos Olímpicos: Puntuaciones y Proyecciones Matemáticas

Durante los Juegos Olímpicos de París 2024, se registraron las puntuaciones máximas de los equipos de Estados Unidos, China y Francia en tres disciplinas deportivas: gimnasia artística, saltos ornamentales (clavados) y tiro con arco.

El evento deportivo tuvo una duración de tres semanas, y se registraron las puntuaciones en las dos primeras semanas. Las matrices $A$ y $B$ representan las puntuaciones máximas de las semanas $1$ y $2$, respectivamente:

1. Determina si los países mejoraron su desempeño en cada disciplina durante la segunda semana con respecto a la primera semana. Muestra los resultados en una matriz  D  e interpreta el elemento  d31.

In [ ]:
import numpy as np

A = np.array([[42,43,31],[40,35,20],[30,15,16]])
B = np.array([[42,43,31],[40,35,20],[30,15,16]])
D = np.subtract(B,A)
print(D)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


2. Después de semanas de competencia la motivación de los deportistas se encuentra en su punto más alto. Debido a esto, analistas deportivos estimaron que en la tercera semana los deportistas podrían mejorar su rendimiento en torno a un  3%  respecto a la primera semana. Representa los resultados que se proyectan para la última semana en la matriz  E  e interpreta el elemento  e22 . Redondea los resultados a la centésima.

In [ ]:
import numpy as np

import numpy as np

A = np.array([[42,43,31],[40,35,20],[30,15,16]])
B = np.array([[42,43,31],[40,35,20],[30,15,16]])
D = np.subtract(B,A)
E = np.multiply(D,0.03)

print(D)
print(E)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Uno de los criterios para determinar el país ganador en las Olimpiadas consiste en asignar puntos a cada tipo de medalla:  3  puntos por una medalla de oro,  2  puntos por una medalla de plata y  1  punto por una medalla de bronce. Luego, se suman los puntos totales para determinar al país con mayor puntaje. Considera que los elementos  fij  de la matriz  F , según el orden en que se mencionan, representan el total de medallas de cada tipo  j  (oro, plata y bronce) obtenidas por el país  i  (Estados Unidos, China y Francia). Por otro lado, la matriz  G  representa el puntaje asignado según el tipo de medalla.
<center>
<img src="https://i.imgur.com/uMMmSHH.png" style="width:31%">
</center>
Representa mediante una matriz  H  el puntaje total obtenido por cada país e interpreta la diferencia  h11−h21 .

In [ ]:
import numpy as np

F = np.array([[42,43,31],[40,35,20],[30,15,16]])
G = np.array([[3],[2],[1]])
H = np.dot(F,G)
print(H)

[[243]
 [210]
 [136]]


4. Durante esta edición de los Juegos Olímpicos, un país obtuvo un total de  10  medallas entre oro, plata y bronce, logrando un puntaje total de  17  puntos ( 3  puntos por cada medalla de oro,  2  puntos por cada medalla de plata y  1  punto por cada medalla de bronce). Además, los deportistas de este país recibieron un aporte estatal de  53  millones de pesos por cada medalla de oro,  40  millones de pesos por cada medalla de plata y  20  millones de pesos por cada medalla de bronce. Con estos datos, se plantea el siguiente sistema de ecuaciones:
<center>
<img src="https://i.imgur.com/8eCmpqQ.png" style="width:24%">
</center>
$\hspace{0.5 cm}$ Donde $x$, $y$ y $z$ representan la cantidad de medallas de oro, plata y bronce obtenidas por el país. Resuelve el sistema de ecuaciones utilizando matrices e interpreta los resultados obtenidos en el contexto del problema.

In [ ]:
import numpy as np

x = np.array([[1,1,1],[3,2,1],[53,40,20]])
y = np.array([[10],[17],[53]])
z = np.linalg.solve(x,y)
print(z)


[[ 41.]
 [-75.]
 [ 44.]]
